version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Setting up Docker...
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      - echo Installing Docker Compose...
      - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - sudo chmod +x /usr/local/bin/docker-compose
      - docker-compose version
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
      - docker login
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $DOCKER_HUB_USERNAME/yugaa-express:latest .
      - docker push $DOCKER_HUB_USERNAME/yugaa-express:latest
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: yes
