name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/yugaa-express:latest
    - name: Debug environment
      run: |
        echo "Listing all env variables (names only):"
        env | cut -d= -f1
        echo "Checking for YOUR_API_KEY:"
        env | grep YOUR_API_KEY

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/yugaa-express:latest
          sudo docker stop yugaa-express || true
          sudo docker rm yugaa-express || true
          sudo docker run -d --name yugaa-express -p 3001:3001 \
          -e CLERK_WEBHOOK_SECRET_KEY=${{ secrets.CLERK_WEBHOOK_SECRET_KEY }} \
          -e CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }} \
          -e CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} \
          -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          -e SHOPIFY_KEY=${{ secrets.SHOPIFY_KEY }} \
          -e LANGCHAIN_TRACING_V2=${{ secrets.LANGCHAIN_TRACING_V2 }} \
          -e SHOPIFY_SECRET_KEY=${{ secrets.SHOPIFY_SECRET_KEY }} \
          -e LANGCHAIN_ENDPOINT=${{ secrets.LANGCHAIN_ENDPOINT }} \
          -e LANGCHAIN_API_KEY=${{ secrets.LANGCHAIN_API_KEY }} \
          -e LANGCHAIN_PROJECT=${{ secrets.LANGCHAIN_PROJECT }} \
          -e LANGCHAIN_CALLBACKS_BACKGROUND=${{ secrets.LANGCHAIN_CALLBACKS_BACKGROUND }} \
          -e PROJECT_ID=${{ secrets.PROJECT_ID }} \
          -e CLIENT_EMAIL=${{ secrets.CLIENT_EMAIL }} \
          -e PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} \
          -e LOGO_BUCKET_NAME=${{ secrets.LOGO_BUCKET_NAME }} \
          -e FILES_BUCKET_NAME=${{ secrets.FILES_BUCKET_NAME }} \
          ${{ secrets.DOCKER_HUB_USERNAME }}/yugaa-express:latest