name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/yugaa-express:latest
    - name: Debug environment
      run: |
        echo "Listing all env variables (names only):"
        env | cut -d= -f1
        echo "Checking for YOUR_API_KEY:"
        env | grep YOUR_API_KEY || echo "YOUR_API_KEY is not set"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
           echo "Starting deployment..."
           sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/yugaa-express:latest
           echo "Docker image pulled"
           sudo docker stop yugaa-express || true
           echo "Stopped existing container if it existed"
           sudo docker rm yugaa-express || true
           echo "Removed existing container if it existed"
           sudo docker run -d --name yugaa-express -p 3001:3001 \
           -e hi=fromhi \
           -e hi_env=fromhi_env \
           ${{ secrets.DOCKER_HUB_USERNAME }}/yugaa-express:latest